defaults:
  - _self_
  - common: common
  - dataset: ds
  - features: features
  - mlflow: mlflow
  - metric: f1
  - model: random_forest
  - prediction: predict

hydra:
  run:
    dir: ${common.artifacts_dir}/${common.run_name}
  sweep:
    dir: ${common.artifacts_dir}/${common.run_name}
    subdir: ${hydra.job.override_dirname}