defaults:
  - _self_
  - model: random_forest

model_path: models/model.pkl
metrics_path: models/metrics.json

download:
  gdrive_id: 141cfvFF5KeEjmRykLJLwkHmmLQZWVMqu
  download_path: data/raw/

splitting_params:
  val_size: 0.2
  random_state: 42

features:
  categorical_features:
    - "ca"
    - "cp"
    - "exang"
    - "fbs"
    - "sex"
    - "restecg"
    - "slope"
    - "thal"
  numerical_features:
    - "age"
    - "chol"
    - "oldpeak"
    - "thalach"
    - "trestbps"
  target: "condition"

mlflow_params:
  mlflow_uri: mlruns
  mlflow_experiment: ml_project

hydra:
  run:
    dir: outputs/${now:%Y-%m-%d_%H-%M-%S}
    sweep:
      dir: outputs/${now:%Y-%m-%d_%H-%M-%S}
      subdir: ${hydra.job.override_dirname}